---
 - name: VPC Creation
   local_action:
     module: ec2_vpc
     region: "{{ region }}"
     state: present
     cidr_block: "{{ cidr_block }}"
     resource_tags: { "Name" : "{{ vpc_name }}"  }
     internet_gateway: True
     subnets:
       "{{ public_subnets + private_subnets }}"
     route_tables:
       - subnets:
           "{{ public_subnets | map(attribute='cidr') | list }}"
         routes:
           - dest: 0.0.0.0/0
             gw: igw
         resource_tags: { "Name" : "{{ vpc_name }}-public-rt" }
   register: vpc

